### ISSUE TITLE
Is it possible to use createLink command?

### ISSUE THREAD

**Issue by udovichenko** [jdaehne/miniRTE#2]
Hi,

The extra is very simple but very useful, thanks!

Is it possible to use createLink command somehow?
I've created the button `{"command":"createLink","icon":"link"}`
But nothing happens when I press it)

To set an URL I need to throw the `prompt('Enter URL')` function as the third argument for `formatText()` function. I can do it by hacking the source code of the miniRTE, but I want to know, is it possible without it. With the help of config or somehow else...

Thank you!

**Comment by jdaehne** [comment]
Thanx. I will have a look into it in the next days... and try to make it possible.

**Comment by udovichenko** [comment]
Wow, it would be great! I'm looking forward to it!

**Comment by hitodev** [comment]
Hi,
I have also tried
{"command":"createLink","icon":"link"}
for a MIGX TV
2 superposed icons appears and nothing happens on click:

[https://imgur.com/XgqbwyT](https://imgur.com/XgqbwyT)

It there a way to add a link command?
Thanks

**Comment by jdaehne** [comment]
Hi,

sorry, i never got the time for testing the link command. I think for links the Redactor Richtext-Editor from modmore is the better solution. You can create custom looks for every TV. That way you can also just have links in the toolbar and limit the height to one line. Redactor also does a much better job on cleanup other html tags.

Link to redactor: https://modmore.com/redactor/

![PastedGraphic-5](https://user-images.githubusercontent.com/10563227/130414970-582c900e-57ed-4308-a9d6-7ff772662e59.png)


I attach the configuration code for our headlines. Just change the buttons to „link“ in the configuration page of the extra.

Best regards
Jan

[redConfigurationSet_quadro-modx-website_2021-08-23@10_22_25.xml.zip](https://github.com/jdaehne/miniRTE/files/7030329/redConfigurationSet_quadro-modx-website_2021-08-23%4010_22_25.xml.zip)
